[project]
name = "DoL-Thalia"

[game]
default_mod_list = "vanilla"
version = "0.5.10.11"

[mod_sources.chinese-localization]
repository = "Eltirosto/Degrees-of-Lewdity-Chinese-Localization"
asset_keywords = ["GameOriginalImagePack", "ModI18N"]
asset_extensions = [".mod.zip"]

[mod_sources.maplebirch-framework]
repository = "MaplebirchLeaf/SCML-DOL-maplebirchFramework"
asset_keywords = ["maplebirch"]
asset_extensions = [".mod.zip", ".modpack"]

[mod_sources."AUfemale"]
asset_extensions = [".zip"]

[mod_sources."AUmale"]
asset_extensions = [".zip"]

[mod_sources."AUandrogynous"]
asset_extensions = [".zip"]

[upstreams.sugarcube_vrelnir]
url = "https://gitgud.io/Vrelnir/sugarcube-2"
ref = "new-year-new-rebase"
path = "vendor/sugarcube-2-vrelnir"

[upstreams.modloader]
url = "https://github.com/MaplebirchLeaf/sugarcube-2-ModLoader"
ref = "thalia"
path = "vendor/sugarcube-2-ModLoader"

[paths]
source_html = "input/game/*.zip"
builtin_mods = "input/mods"
output_html = "dist/html/index.html"
output_zip = "dist/zip/DoL-Thalia.zip"
output_apk_dir = "dist/apk"
story_format = "dist/story-format/sugarcube-2/format.js"
cordova_project = ".cache/apk/dol-thalia-android"

[apk]
id = "com.maplebirch.dol.thalia"
name = "DoL Thalia"
